### ISSUE TITLE
Content Errors Page due to NullPointerException

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-api#70]
There's some content caching issue (getContentByID) that throws a null pointer exception when visiting the content problems page.

**Comment by jsharkey13** [comment]
I think this was fixed in https://github.com/ucam-cl-dtg/isaac-api/commit/2e762220829430e62a810006d192c3c8c3f73c83, but a new form has recurred here: https://github.com/ucam-cl-dtg/isaac-app/issues/834
