### ISSUE TITLE
Add HSTS headers and preload

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-api#81]
We should add HSTS CSP headers to the api proxy to ensure https is enforced a the browser level and susceptible to MITM attacks.

https://www.youtube.com/watch?v=zPhi_fzVbh8

**Comment by jsharkey13** [comment]
https://github.com/ucam-cl-dtg/isaac-router/commit/0f2458802b68c9e60726c96657e91a64d5ebe585

https://hstspreload.org/?domain=isaacphysics.org
